name: daily quote

permissions:
    contents: write

on:
    # Notion Cron Job이 정확하게 자정에 가동하지 않으므로 01시(UTC+9)로 적용
    schedule:
        - cron: '0 16 * * *'

env:
    NOTION_API: ${{ secrets.NOTION_API}}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: pip install -r requirements.txt
            - run: python daily_quote.py