name: daily quote

permissions:
    contents: write

on:
    schedule:
        - cron: '0/5 * * * *'

jobs:
    env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NOTION_API: ${{ secrets.NOTION_API }}

    run:
        environment: notion_daily_quote
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: pip install -r requirements.txt
            - run: python daily_quote.py